import = ["~/.config/alacritty/rose-pine-moon.toml"]

[window]
dynamic_padding = true
padding = { x = 10, y = 10 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12
