# ===================================
# Startup Applications
# ===================================

exec-once = /run/current-system/sw/bin/quickshell -n
exec-once = swaync
exec-once = hypridle
exec-once = /run/current-system/sw/bin/awww-daemon
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprpolkitagent
exec-once = /run/current-system/sw/bin/elephant
exec-once = /run/current-system/sw/bin/walker --gapplication-service
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = ~/.config/hypr/scripts/wallpaper-switcher.sh
