# ===================================
# Startup Applications
# ===================================

exec-once = waybar
exec-once = swaync
exec-once = hypridle
exec-once = swww-daemon
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprpolkitagent
exec-once = /run/current-system/sw/bin/elephant
exec-once = /run/current-system/sw/bin/walker --gapplication-service
exec-once = ~/.config/hypr/scripts/wallpaper-switcher.sh
