# ===================================
# Hyprland Configuration Entrypoint
# ===================================

source = monitors.conf
source = input.conf
source = appearance.conf
source = theme.conf
source = binds.conf
source = submaps.conf
source = workspaces.conf
source = rules.conf
source = autostart.conf
source = profile.conf
