# ===================================
# Personal Profile Overrides
# ===================================

decoration {
    blur {
        size = 10
        passes = 3
        vibrancy = 0.2
        vibrancy_darkness = 0.3
    }
}

general {
    gaps_in = 6
    gaps_out = 12
}

exec-once = ~/.config/hypr/scripts/generate-dots-wallpaper.py
