# ===================================
# Submaps
# ===================================

submap = resize

bind = , escape, submap, reset
bind = , Return, submap, reset
bind = , H, resizeactive, -50 0
bind = , L, resizeactive, 50 0
bind = , K, resizeactive, 0 -50
bind = , J, resizeactive, 0 50
bind = , left, resizeactive, -50 0
bind = , right, resizeactive, 50 0
bind = , up, resizeactive, 0 -50
bind = , down, resizeactive, 0 50

submap = session

bind = , escape, submap, reset
bind = , Return, submap, reset
bind = , L, exec, hyprlock
bind = , S, exec, systemctl suspend
bind = , E, exit
bind = , R, exec, systemctl reboot
bind = , P, exec, systemctl poweroff

submap = media

bind = , escape, submap, reset
bind = , Return, submap, reset
bind = , space, exec, playerctl play-pause
bind = , N, exec, playerctl next
bind = , P, exec, playerctl previous
bind = , M, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , up, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , down, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

submap = window

bind = , escape, submap, reset
bind = , Return, submap, reset
bind = , P, pseudo
bind = , I, pin

submap = reset
