{lib, ...}: let
  # Profile-based defaults for Ghostty configuration
  profileDefaults = {
    personal = {
      theme = "Synthwave";
      font-family = "JetBrainsMono Nerd Font Mono";
      font-size = 13;
      background-opacity = 1.0;
      cursor-style = "block";
    };
    work = {
      theme = "Github Dark";
      font-family = "JetBrainsMono Nerd Font Mono";
      font-size = 13;
      background-opacity = 1.0;
      cursor-style = "block";
    };
  };

  # Resolve ghostty config for a user (profile defaults + per-user overrides)
  getGhosttyConfig = user: let
    defaults = profileDefaults.${user.profile};
  in {
    theme =
      if user.ghostty.theme != null
      then user.ghostty.theme
      else defaults.theme;
    font-family =
      if user.ghostty.font-family != null
      then user.ghostty.font-family
      else defaults.font-family;
    font-size =
      if user.ghostty.font-size != null
      then user.ghostty.font-size
      else defaults.font-size;
    background-opacity =
      if user.ghostty.background-opacity != null
      then user.ghostty.background-opacity
      else defaults.background-opacity;
    cursor-style =
      if user.ghostty.cursor-style != null
      then user.ghostty.cursor-style
      else defaults.cursor-style;
    extraConfig = user.ghostty.extraConfig;
  };

  # Generate ghostty config content
  mkGhosttyConfig = settings: ''
    # Generated by Nix - Do not edit manually
    # This file is managed declaratively via NixOS/nix-darwin configuration

    # Theme
    theme = ${settings.theme}

    # Font configuration
    font-family = ${settings.font-family}
    font-size = ${toString settings.font-size}

    # Appearance
    background-opacity = ${toString settings.background-opacity}
    cursor-style = ${settings.cursor-style}

    # Shell configuration
    # Launch Zellij directly, which will use nushell (configured in zellij.kdl)
    # This creates the chain: Ghostty -> Zellij -> Nushell
    command = /run/current-system/sw/bin/zellij
    shell-integration = detect

    # Unbind macOS keys so they are forwarded to Zellij
    # This allows Zellij to handle tabs instead of Ghostty
    keybind = cmd+t=unbind
    keybind = cmd+n=unbind
    keybind = cmd+c=unbind
    keybind = cmd+w=unbind
    keybind = cmd+opt+left=unbind
    keybind = cmd+opt+right=unbind

    # Additional user configuration
    ${settings.extraConfig}
  '';
in {
  mkGhosttyScript = {
    user,
    homeDir,
    enabled,
  }: let
    ghosttyConfig = getGhosttyConfig user;
    configContent = mkGhosttyConfig ghosttyConfig;
  in
    lib.optionalString enabled ''
      # Ghostty configuration
      [ -L "${homeDir}/.config/ghostty/config" ] && rm "${homeDir}/.config/ghostty/config"
      cat > "${homeDir}/.config/ghostty/config" << 'EOFGHOSTTY'
      ${configContent}
      EOFGHOSTTY
      chmod 644 "${homeDir}/.config/ghostty/config"

      # Deploy custom themes if any exist
      ${lib.optionalString (builtins.pathExists ../files/ghostty/themes) ''
        for theme in ${../files/ghostty/themes}/*; do
          if [ -f "$theme" ]; then
            cp "$theme" "${homeDir}/.config/ghostty/themes/"
            chmod 644 "${homeDir}/.config/ghostty/themes/$(basename "$theme")"
          fi
        done
      ''}
    '';
}
