name: PR Checks
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v17
      - name: Lint Nix Files
        run: nix develop --command alejandra -c .
